### ISSUE TITLE
Too stupid to run it, sorry

### ISSUE THREAD

**Issue by chatterbro** [alfred82santa/whalesong#10]
Hey, I actually just want to mess around with some of the functions you've build in the JS.

I've tried pasting the whole JS in the console of a running Whatsapp Web Session in Chrome and it did find the modules and everything but I couldn't find a variable where to access the Managers etc. Like, what is the root variable where you put everything that the python scripts can access then?

If it's too hard interacting with the JS that way, I'd be grateful if you could explain running the python code to me. I've googled a lot to even get it installed but running the init.py directly in the terminal gives me ` No module named '__main__.driver'; '__main__' is not a package`. Removing '__main__.' as in making it only say `driver` in the import statement works at least for this issue, but continuing this throughout the other files causes other issues.

I am using python3.7 on macOS

Thank you

EDIT: I personally have no need for it anymore, I was able to solve my issue without this API. Still, very good work, I am seriously amazed!

**Comment by alfred82santa** [comment]
In order to play with whalesong on Chrome, you could paste content of file `js/whalesong.js` built with `make build-js` on debug console. It will create a variable `window.manager`. This variable is the base of whalesong.

Manager has a method called `executeCommand`. It is used to execute command in submanagers.
https://github.com/alfred82santa/whalesong/blob/master/js/src/manager.js#L269

`exId` parameter is an execution identifier (it must be unique for each execution), you need it to retrieve execution results (final results, partial results used for iterators and monitors, and error results). 

`command` parameter is a string to identify the method you want execute. It is a path to method indeed. It means if you want to execute a method `bar` in submanager `foo`, the string must be `foo|bar`.

`params` is an object with method params.

In order to retrieve results you could use:
window.manager.resultManager._results[yourExId]

About how to use from python. I don't understand what you have tried to do. Whalesong has no `init.py` file.
